### ISSUE TITLE
Confused of loss=nan

### ISSUE THREAD

**Issue by EnQing626** [cdoersch/vae_tutorial#1]
I have some trouble happening with loss=nan. I am confused why it happened by using my own data. 
I modify the "batch size" from 100 to 1, and then, modify the param of "Dummydata" shape dim from 100 to 1. But I don't know whether should I modify Reduction loss_weight. Is that the key factor influencing the mistake result loss=nan?

**Comment by cdoersch** [comment]
Sorry CJEQ, I think StackOverflow would be a better place for a question like this.  I want to keep the github issues for this project focused on potential changes to the codebase that's hosted here.
