### ISSUE TITLE
got the error "Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 0) "

### ISSUE THREAD

**Issue by peaceorwell** [cdoersch/vae_tutorial#3]
When i run **python mnist_vae.py**, got "**Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 0) Incompatible number of blobs for layer decode4**". This error come from 'net=caffe.Net('mnist_vae.prototxt','snapshots/mnist_vae_iter_60000.caffemodel', caffe.TEST'.
I have checked the code,but found nothing wrong. hope for your help! :sob:

**Comment by cdoersch** [comment]
I haven't seen an error like this one before.  Did you get this with the exact code that's currently in the repository, or have you modified it somehow?

seanbell explains more about what this error message means here: https://github.com/BVLC/caffe/issues/2784 

In the future, please include the full error message.

**Comment by peaceorwell** [comment]
Thank you, I had changed some layers before.When I revert the commit,it runs without error! :+1:
