### ISSUE TITLE
The kldiv(power) layer

### ISSUE THREAD

**Issue by syllcs** [cdoersch/vae_tutorial#6]
Thank you for this great tutorial and the code. But I have trouble understanding the kldiv(Power) layer in mnist_vae. According to the tutorial, the loss function should contain D[Q(z|X)||P(z)], not exp(D[Q(z|X)||P(z)]). So why do we need this layer?

**Comment by cdoersch** [comment]
The default exponent for the power layer is 1.  This layer is actually just subtracting 0.5, which is a part of the standard kl-divergence computation.
